[project]
name = "labelme2yolo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.2.1",
    "jinja2>=3.1.6",
    "tqdm>=4.67.1",
]
